name: smart_campus_app
description: A Smart Campus App for Babcock University students
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.0
  flutter_svg: ^2.2.0
  lottie: ^2.7.0
  provider: ^6.1.5
  http: ^1.5.0
  dio: ^5.9.0
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  google_maps_flutter: ^2.12.3
  geolocator: ^10.1.1
  geocoding: ^2.2.2
  flutter_local_notifications: ^16.3.3
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  intl: ^0.18.1
  permission_handler: ^11.4.0
  connectivity_plus: ^5.0.2
  flutter_native_splash: ^2.4.4
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  
  assets:
    - assets/animations/ 